name: image_picker_plus_workspace
publish_to: none

environment:
  sdk: '>=3.12.0 <4.0.0'

workspace:
  - packages/image_picker_pluz
  - packages/image_picker_plus_platform_interface
  - packages/image_picker_plus_android
  - packages/image_picker_plus_ios
  - packages/image_picker_plus_windows
  - packages/image_picker_plus_macos
  - packages/image_picker_plus_linux
  - packages/image_picker_plus_for_web
  - packages/image_picker_pluz/example

dev_dependencies:
  melos: ^8.6.0

melos:
  scripts:
    analyze:
      run: fvm dart run melos exec --concurrency=1 --fail-fast -- flutter analyze --no-pub
      description: Analyze all workspace packages.
    test:
      run: fvm dart run melos exec --concurrency=1 --dir-exists=test --fail-fast -- flutter test --no-pub
      description: Run tests in every package that has a test directory.
