// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v26.1.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.flutter.plugins.imagepicker

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class SourceCamera(val raw: Int) {
  REAR(0),
  FRONT(1);

  companion object {
    fun ofRaw(raw: Int): SourceCamera? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class SourceType(val raw: Int) {
  CAMERA(0),
  GALLERY(1);

  companion object {
    fun ofRaw(raw: Int): SourceType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CacheRetrievalType(val raw: Int) {
  IMAGE(0),
  VIDEO(1);

  companion object {
    fun ofRaw(raw: Int): CacheRetrievalType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GeneralOptions (
  val allowMultiple: Boolean,
  val usePhotoPicker: Boolean,
  val limit: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GeneralOptions {
      val allowMultiple = pigeonVar_list[0] as Boolean
      val usePhotoPicker = pigeonVar_list[1] as Boolean
      val limit = pigeonVar_list[2] as Long?
      return GeneralOptions(allowMultiple, usePhotoPicker, limit)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      allowMultiple,
      usePhotoPicker,
      limit,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is GeneralOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Options for image selection and output.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ImageSelectionOptions (
  /** If set, the max width that the image should be resized to fit in. */
  val maxWidth: Double? = null,
  /** If set, the max height that the image should be resized to fit in. */
  val maxHeight: Double? = null,
  /**
   * The quality of the output image, from 0-100.
   *
   * 100 indicates original quality.
   */
  val quality: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ImageSelectionOptions {
      val maxWidth = pigeonVar_list[0] as Double?
      val maxHeight = pigeonVar_list[1] as Double?
      val quality = pigeonVar_list[2] as Long
      return ImageSelectionOptions(maxWidth, maxHeight, quality)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maxWidth,
      maxHeight,
      quality,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ImageSelectionOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaSelectionOptions (
  val imageSelectionOptions: ImageSelectionOptions
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaSelectionOptions {
      val imageSelectionOptions = pigeonVar_list[0] as ImageSelectionOptions
      return MediaSelectionOptions(imageSelectionOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      imageSelectionOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MediaSelectionOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Options for image selection and output.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VideoSelectionOptions (
  /** The maximum desired length for the video, in seconds. */
  val maxDurationSeconds: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoSelectionOptions {
      val maxDurationSeconds = pigeonVar_list[0] as Long?
      return VideoSelectionOptions(maxDurationSeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      maxDurationSeconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is VideoSelectionOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Represents a picked media file with its path and original content URI.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PickedMedia (
  /** The file system path to the picked media. */
  val path: String,
  /** The original content:// URI from the Android system picker. */
  val contentUri: String? = null,
  /** The MIME type of the media (e.g., "image/jpeg", "video/mp4"). */
  val mimeType: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PickedMedia {
      val path = pigeonVar_list[0] as String
      val contentUri = pigeonVar_list[1] as String?
      val mimeType = pigeonVar_list[2] as String?
      return PickedMedia(path, contentUri, mimeType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      contentUri,
      mimeType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PickedMedia) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Specification for the source of an image or video selection.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SourceSpecification (
  val type: SourceType,
  val camera: SourceCamera? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SourceSpecification {
      val type = pigeonVar_list[0] as SourceType
      val camera = pigeonVar_list[1] as SourceCamera?
      return SourceSpecification(type, camera)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      camera,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SourceSpecification) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * An error that occurred during lost result retrieval.
 *
 * The data here maps to the `PlatformException` that will be created from it.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CacheRetrievalError (
  val code: String,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CacheRetrievalError {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String?
      return CacheRetrievalError(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CacheRetrievalError) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * The result of retrieving cached results from a previous run.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CacheRetrievalResult (
  /** The type of the retrieved data. */
  val type: CacheRetrievalType,
  /** The error from the last selection, if any. */
  val error: CacheRetrievalError? = null,
  /** The results from the last selection, if any. */
  val paths: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CacheRetrievalResult {
      val type = pigeonVar_list[0] as CacheRetrievalType
      val error = pigeonVar_list[1] as CacheRetrievalError?
      val paths = pigeonVar_list[2] as List<String>
      return CacheRetrievalResult(type, error, paths)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      error,
      paths,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CacheRetrievalResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SourceCamera.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SourceType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CacheRetrievalType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GeneralOptions.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ImageSelectionOptions.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaSelectionOptions.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoSelectionOptions.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PickedMedia.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SourceSpecification.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CacheRetrievalError.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CacheRetrievalResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SourceCamera -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is SourceType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is CacheRetrievalType -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is GeneralOptions -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ImageSelectionOptions -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MediaSelectionOptions -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is VideoSelectionOptions -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PickedMedia -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is SourceSpecification -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is CacheRetrievalError -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is CacheRetrievalResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ImagePickerApi {
  /** Selects images and returns their paths with content URIs. */
  fun pickImages(source: SourceSpecification, options: ImageSelectionOptions, generalOptions: GeneralOptions, callback: (Result<List<PickedMedia>>) -> Unit)
  /** Selects video and returns their paths with content URIs. */
  fun pickVideos(source: SourceSpecification, options: VideoSelectionOptions, generalOptions: GeneralOptions, callback: (Result<List<PickedMedia>>) -> Unit)
  /** Selects images and videos and returns their paths with content URIs. */
  fun pickMedia(mediaSelectionOptions: MediaSelectionOptions, generalOptions: GeneralOptions, callback: (Result<List<PickedMedia>>) -> Unit)
  /** Returns results from a previous app session, if any. */
  fun retrieveLostResults(): CacheRetrievalResult?

  companion object {
    /** The codec used by ImagePickerApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ImagePickerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ImagePickerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_picker_plus_android.ImagePickerApi.pickImages$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as SourceSpecification
            val optionsArg = args[1] as ImageSelectionOptions
            val generalOptionsArg = args[2] as GeneralOptions
            api.pickImages(sourceArg, optionsArg, generalOptionsArg) { result: Result<List<PickedMedia>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_picker_plus_android.ImagePickerApi.pickVideos$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as SourceSpecification
            val optionsArg = args[1] as VideoSelectionOptions
            val generalOptionsArg = args[2] as GeneralOptions
            api.pickVideos(sourceArg, optionsArg, generalOptionsArg) { result: Result<List<PickedMedia>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_picker_plus_android.ImagePickerApi.pickMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mediaSelectionOptionsArg = args[0] as MediaSelectionOptions
            val generalOptionsArg = args[1] as GeneralOptions
            api.pickMedia(mediaSelectionOptionsArg, generalOptionsArg) { result: Result<List<PickedMedia>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.image_picker_plus_android.ImagePickerApi.retrieveLostResults$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.retrieveLostResults())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
