// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum SourceCamera: Int {
  case rear = 0
  case front = 1
}

enum SourceType: Int {
  case camera = 0
  case gallery = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct MaxSize: Hashable {
  var width: Double? = nil
  var height: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MaxSize? {
    let width: Double? = nilOrValue(pigeonVar_list[0])
    let height: Double? = nilOrValue(pigeonVar_list[1])

    return MaxSize(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
  static func == (lhs: MaxSize, rhs: MaxSize) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaSelectionOptions: Hashable {
  var maxSize: MaxSize
  var imageQuality: Int64? = nil
  var requestFullMetadata: Bool
  var allowMultiple: Bool
  var limit: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaSelectionOptions? {
    let maxSize = pigeonVar_list[0] as! MaxSize
    let imageQuality: Int64? = nilOrValue(pigeonVar_list[1])
    let requestFullMetadata = pigeonVar_list[2] as! Bool
    let allowMultiple = pigeonVar_list[3] as! Bool
    let limit: Int64? = nilOrValue(pigeonVar_list[4])

    return MediaSelectionOptions(
      maxSize: maxSize,
      imageQuality: imageQuality,
      requestFullMetadata: requestFullMetadata,
      allowMultiple: allowMultiple,
      limit: limit
    )
  }
  func toList() -> [Any?] {
    return [
      maxSize,
      imageQuality,
      requestFullMetadata,
      allowMultiple,
      limit,
    ]
  }
  static func == (lhs: MediaSelectionOptions, rhs: MediaSelectionOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PickedMedia: Hashable {
  var path: String
  var localIdentifier: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PickedMedia? {
    let path = pigeonVar_list[0] as! String
    let localIdentifier: String? = nilOrValue(pigeonVar_list[1])

    return PickedMedia(
      path: path,
      localIdentifier: localIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      localIdentifier,
    ]
  }
  static func == (lhs: PickedMedia, rhs: PickedMedia) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SourceSpecification: Hashable {
  var type: SourceType
  var camera: SourceCamera


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SourceSpecification? {
    let type = pigeonVar_list[0] as! SourceType
    let camera = pigeonVar_list[1] as! SourceCamera

    return SourceSpecification(
      type: type,
      camera: camera
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      camera,
    ]
  }
  static func == (lhs: SourceSpecification, rhs: SourceSpecification) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SourceCamera(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SourceType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return MaxSize.fromList(self.readValue() as! [Any?])
    case 132:
      return MediaSelectionOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return PickedMedia.fromList(self.readValue() as! [Any?])
    case 134:
      return SourceSpecification.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SourceCamera {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SourceType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? MaxSize {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? MediaSelectionOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PickedMedia {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? SourceSpecification {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ImagePickerApi {
  func pickImage(withSource source: SourceSpecification, maxSize: MaxSize, quality imageQuality: Int64?, fullMetadata requestFullMetadata: Bool, completion: @escaping (Result<PickedMedia?, Error>) -> Void)
  func pickMultiImage(withMaxSize maxSize: MaxSize, quality imageQuality: Int64?, fullMetadata requestFullMetadata: Bool, limit: Int64?, completion: @escaping (Result<[PickedMedia], Error>) -> Void)
  func pickVideo(withSource source: SourceSpecification, maxDuration maxDurationSeconds: Int64?, completion: @escaping (Result<PickedMedia?, Error>) -> Void)
  func pickMultiVideo(withMaxDuration maxDurationSeconds: Int64?, limit: Int64?, completion: @escaping (Result<[PickedMedia], Error>) -> Void)
  /// Selects images and videos and returns their paths.
  func pickMedia(withMediaSelectionOptions mediaSelectionOptions: MediaSelectionOptions, completion: @escaping (Result<[PickedMedia], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ImagePickerApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ImagePickerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ImagePickerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let pickImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_picker_plus_ios.ImagePickerApi.pickImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourceArg = args[0] as! SourceSpecification
        let maxSizeArg = args[1] as! MaxSize
        let imageQualityArg: Int64? = nilOrValue(args[2])
        let requestFullMetadataArg = args[3] as! Bool
        api.pickImage(withSource: sourceArg, maxSize: maxSizeArg, quality: imageQualityArg, fullMetadata: requestFullMetadataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickImageChannel.setMessageHandler(nil)
    }
    let pickMultiImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_picker_plus_ios.ImagePickerApi.pickMultiImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickMultiImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let maxSizeArg = args[0] as! MaxSize
        let imageQualityArg: Int64? = nilOrValue(args[1])
        let requestFullMetadataArg = args[2] as! Bool
        let limitArg: Int64? = nilOrValue(args[3])
        api.pickMultiImage(withMaxSize: maxSizeArg, quality: imageQualityArg, fullMetadata: requestFullMetadataArg, limit: limitArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickMultiImageChannel.setMessageHandler(nil)
    }
    let pickVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_picker_plus_ios.ImagePickerApi.pickVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourceArg = args[0] as! SourceSpecification
        let maxDurationSecondsArg: Int64? = nilOrValue(args[1])
        api.pickVideo(withSource: sourceArg, maxDuration: maxDurationSecondsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickVideoChannel.setMessageHandler(nil)
    }
    let pickMultiVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_picker_plus_ios.ImagePickerApi.pickMultiVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickMultiVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let maxDurationSecondsArg: Int64? = nilOrValue(args[0])
        let limitArg: Int64? = nilOrValue(args[1])
        api.pickMultiVideo(withMaxDuration: maxDurationSecondsArg, limit: limitArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickMultiVideoChannel.setMessageHandler(nil)
    }
    /// Selects images and videos and returns their paths.
    let pickMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.image_picker_plus_ios.ImagePickerApi.pickMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mediaSelectionOptionsArg = args[0] as! MediaSelectionOptions
        api.pickMedia(withMediaSelectionOptions: mediaSelectionOptionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickMediaChannel.setMessageHandler(nil)
    }
  }
}
