// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon, do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Flutter
import Foundation

// MARK: - Enums

public enum FLTSourceCamera: Int {
    case rear = 0
    case front = 1
}

public enum FLTSourceType: Int {
    case camera = 0
    case gallery = 1
}

// MARK: - Data Classes

public class FLTMaxSize {
    public var width: NSNumber?
    public var height: NSNumber?

    public init(width: NSNumber? = nil, height: NSNumber? = nil) {
        self.width = width
        self.height = height
    }

    static func fromList(_ list: [Any?]) -> FLTMaxSize {
        let result = FLTMaxSize()
        result.width = list[0] as? NSNumber
        result.height = list[1] as? NSNumber
        return result
    }

    func toList() -> [Any?] {
        return [width, height]
    }
}

public class FLTMediaSelectionOptions {
    public var maxSize: FLTMaxSize
    public var imageQuality: NSNumber?
    public var requestFullMetadata: Bool
    public var allowMultiple: Bool
    public var limit: NSNumber?

    public init(
        maxSize: FLTMaxSize,
        imageQuality: NSNumber? = nil,
        requestFullMetadata: Bool,
        allowMultiple: Bool,
        limit: NSNumber? = nil
    ) {
        self.maxSize = maxSize
        self.imageQuality = imageQuality
        self.requestFullMetadata = requestFullMetadata
        self.allowMultiple = allowMultiple
        self.limit = limit
    }

    static func fromList(_ list: [Any?]) -> FLTMediaSelectionOptions {
        let maxSize = list[0] as! FLTMaxSize
        let imageQuality = list[1] as? NSNumber
        let requestFullMetadata = list[2] as! Bool
        let allowMultiple = list[3] as! Bool
        let limit = list[4] as? NSNumber
        return FLTMediaSelectionOptions(
            maxSize: maxSize,
            imageQuality: imageQuality,
            requestFullMetadata: requestFullMetadata,
            allowMultiple: allowMultiple,
            limit: limit
        )
    }

    func toList() -> [Any?] {
        return [maxSize, imageQuality, requestFullMetadata, allowMultiple, limit]
    }
}

public class FLTSourceSpecification {
    public var type: FLTSourceType
    public var camera: FLTSourceCamera

    public init(type: FLTSourceType, camera: FLTSourceCamera) {
        self.type = type
        self.camera = camera
    }

    static func fromList(_ list: [Any?]) -> FLTSourceSpecification {
        let type: FLTSourceType
        if let enumValue = list[0] as? FLTSourceType {
            type = enumValue
        } else if let numValue = list[0] as? NSNumber {
            type = FLTSourceType(rawValue: numValue.intValue)!
        } else {
            type = .camera
        }

        let camera: FLTSourceCamera
        if let enumValue = list[1] as? FLTSourceCamera {
            camera = enumValue
        } else if let numValue = list[1] as? NSNumber {
            camera = FLTSourceCamera(rawValue: numValue.intValue)!
        } else {
            camera = .rear
        }

        return FLTSourceSpecification(type: type, camera: camera)
    }

    func toList() -> [Any?] {
        return [type.rawValue, camera.rawValue]
    }
}

// MARK: - Codec

private class MessagesPigeonCodecReader: FlutterStandardReader {
    override func readValue(ofType type: UInt8) -> Any? {
        switch type {
        case 129:
            return FLTSourceCamera(rawValue: (readValue() as! NSNumber).intValue)
        case 130:
            return FLTSourceType(rawValue: (readValue() as! NSNumber).intValue)
        case 131:
            return FLTMaxSize.fromList(readValue() as! [Any?])
        case 132:
            return FLTMediaSelectionOptions.fromList(readValue() as! [Any?])
        case 133:
            return FLTSourceSpecification.fromList(readValue() as! [Any?])
        default:
            return super.readValue(ofType: type)
        }
    }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
    override func writeValue(_ value: Any) {
        if let camera = value as? FLTSourceCamera {
            writeByte(129)
            writeValue(camera.rawValue)
        } else if let sourceType = value as? FLTSourceType {
            writeByte(130)
            writeValue(sourceType.rawValue)
        } else if let maxSize = value as? FLTMaxSize {
            writeByte(131)
            writeValue(maxSize.toList())
        } else if let options = value as? FLTMediaSelectionOptions {
            writeByte(132)
            writeValue(options.toList())
        } else if let spec = value as? FLTSourceSpecification {
            writeByte(133)
            writeValue(spec.toList())
        } else {
            super.writeValue(value)
        }
    }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
    override func reader(with data: Data) -> FlutterStandardReader {
        return MessagesPigeonCodecReader(data: data)
    }

    override func writer(with data: NSMutableData) -> FlutterStandardWriter {
        return MessagesPigeonCodecWriter(data: data)
    }
}

private var messagesCodec: FlutterStandardMessageCodec = {
    let readerWriter = MessagesPigeonCodecReaderWriter()
    return FlutterStandardMessageCodec(readerWriter: readerWriter)
}()

// MARK: - Protocol

public protocol FLTImagePickerApi {
    func pickImage(
        withSource source: FLTSourceSpecification,
        maxSize: FLTMaxSize,
        quality imageQuality: NSNumber?,
        fullMetadata: Bool,
        completion: @escaping (String?, FlutterError?) -> Void
    )

    func pickMultiImage(
        withMaxSize maxSize: FLTMaxSize,
        quality imageQuality: NSNumber?,
        fullMetadata: Bool,
        limit: NSNumber?,
        completion: @escaping ([String]?, FlutterError?) -> Void
    )

    func pickVideo(
        withSource source: FLTSourceSpecification,
        maxDuration maxDurationSeconds: NSNumber?,
        completion: @escaping (String?, FlutterError?) -> Void
    )

    func pickMultiVideo(
        withMaxDuration maxDurationSeconds: NSNumber?,
        limit: NSNumber?,
        completion: @escaping ([String]?, FlutterError?) -> Void
    )

    func pickMedia(
        withMediaSelectionOptions options: FLTMediaSelectionOptions,
        completion: @escaping ([String]?, FlutterError?) -> Void
    )
}

// MARK: - Setup

private func wrapResult(_ result: Any?, _ error: FlutterError?) -> [Any?] {
    if let error = error {
        return [error.code, error.message, error.details]
    }
    return [result]
}

private func getNullableObject(at index: Int, from array: [Any?]) -> Any? {
    let result = array[index]
    return result is NSNull ? nil : result
}

public func SetUpFLTImagePickerApi(_ binaryMessenger: FlutterBinaryMessenger, _ api: FLTImagePickerApi?) {
    SetUpFLTImagePickerApiWithSuffix(binaryMessenger, api, "")
}

public func SetUpFLTImagePickerApiWithSuffix(_ binaryMessenger: FlutterBinaryMessenger, _ api: FLTImagePickerApi?, _ messageChannelSuffix: String) {
    let suffix = messageChannelSuffix.isEmpty ? "" : ".\(messageChannelSuffix)"

    // pickImage
    let pickImageChannel = FlutterBasicMessageChannel(
        name: "dev.flutter.pigeon.image_picker_plus_ios.ImagePickerApi.pickImage\(suffix)",
        binaryMessenger: binaryMessenger,
        codec: messagesCodec
    )
    if let api = api {
        pickImageChannel.setMessageHandler { message, reply in
            let args = message as! [Any?]
            let source = args[0] as! FLTSourceSpecification
            let maxSize = args[1] as! FLTMaxSize
            let imageQuality = getNullableObject(at: 2, from: args) as? NSNumber
            let requestFullMetadata = args[3] as! Bool
            api.pickImage(withSource: source, maxSize: maxSize, quality: imageQuality, fullMetadata: requestFullMetadata) { result, error in
                reply(wrapResult(result, error))
            }
        }
    } else {
        pickImageChannel.setMessageHandler(nil)
    }

    // pickMultiImage
    let pickMultiImageChannel = FlutterBasicMessageChannel(
        name: "dev.flutter.pigeon.image_picker_plus_ios.ImagePickerApi.pickMultiImage\(suffix)",
        binaryMessenger: binaryMessenger,
        codec: messagesCodec
    )
    if let api = api {
        pickMultiImageChannel.setMessageHandler { message, reply in
            let args = message as! [Any?]
            let maxSize = args[0] as! FLTMaxSize
            let imageQuality = getNullableObject(at: 1, from: args) as? NSNumber
            let requestFullMetadata = args[2] as! Bool
            let limit = getNullableObject(at: 3, from: args) as? NSNumber
            api.pickMultiImage(withMaxSize: maxSize, quality: imageQuality, fullMetadata: requestFullMetadata, limit: limit) { result, error in
                reply(wrapResult(result, error))
            }
        }
    } else {
        pickMultiImageChannel.setMessageHandler(nil)
    }

    // pickVideo
    let pickVideoChannel = FlutterBasicMessageChannel(
        name: "dev.flutter.pigeon.image_picker_plus_ios.ImagePickerApi.pickVideo\(suffix)",
        binaryMessenger: binaryMessenger,
        codec: messagesCodec
    )
    if let api = api {
        pickVideoChannel.setMessageHandler { message, reply in
            let args = message as! [Any?]
            let source = args[0] as! FLTSourceSpecification
            let maxDurationSeconds = getNullableObject(at: 1, from: args) as? NSNumber
            api.pickVideo(withSource: source, maxDuration: maxDurationSeconds) { result, error in
                reply(wrapResult(result, error))
            }
        }
    } else {
        pickVideoChannel.setMessageHandler(nil)
    }

    // pickMultiVideo
    let pickMultiVideoChannel = FlutterBasicMessageChannel(
        name: "dev.flutter.pigeon.image_picker_plus_ios.ImagePickerApi.pickMultiVideo\(suffix)",
        binaryMessenger: binaryMessenger,
        codec: messagesCodec
    )
    if let api = api {
        pickMultiVideoChannel.setMessageHandler { message, reply in
            let args = message as! [Any?]
            let maxDurationSeconds = getNullableObject(at: 0, from: args) as? NSNumber
            let limit = getNullableObject(at: 1, from: args) as? NSNumber
            api.pickMultiVideo(withMaxDuration: maxDurationSeconds, limit: limit) { result, error in
                reply(wrapResult(result, error))
            }
        }
    } else {
        pickMultiVideoChannel.setMessageHandler(nil)
    }

    // pickMedia
    let pickMediaChannel = FlutterBasicMessageChannel(
        name: "dev.flutter.pigeon.image_picker_plus_ios.ImagePickerApi.pickMedia\(suffix)",
        binaryMessenger: binaryMessenger,
        codec: messagesCodec
    )
    if let api = api {
        pickMediaChannel.setMessageHandler { message, reply in
            let args = message as! [Any?]
            let mediaSelectionOptions = args[0] as! FLTMediaSelectionOptions
            api.pickMedia(withMediaSelectionOptions: mediaSelectionOptions) { result, error in
                reply(wrapResult(result, error))
            }
        }
    } else {
        pickMediaChannel.setMessageHandler(nil)
    }
}
